# Tensors
- similar to NumPy's ndarrays
- can run on specialized hardware to accelerate computing (e.g. GPU)

In [ ]:
import torch
import numpy as np

__1. Initialization__

In [ ]:
data=[[1,2],[3,4]]
x_data=torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [ ]:
np_array=np.array(data)
x_np=torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


In [ ]:
x_ones=torch.ones_like(x_data) # retain shape and dtype
print(x_ones)
x_rand=torch.rand_like(x_data,dtype=torch.float) # override dtype
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.3155, 0.2550],
        [0.0944, 0.5485]])


In [ ]:
shape=(2,3,)
rand_tensor=torch.rand(shape)
ones_tensor=torch.ones(shape)
print(rand_tensor)
print(ones_tensor)

tensor([[0.6460, 0.8682, 0.7823],
        [0.5118, 0.7519, 0.0928]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


__2. Attributes__

In [ ]:
tensor=torch.rand(3,4)
print(tensor.shape,tensor.dtype,tensor.device)

torch.Size([3, 4]) torch.float32 cpu


__3. Operations__
- over 100 tensor operations [here](https://pytorch.org/docs/stable/torch.html)

In [ ]:
# move tensor to GPU if available
if torch.cuda.is_available():
    tensor=tensor.to('cuda')

In [ ]:
tensor=torch.ones(4,4)
tensor[:,1]=0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
t1=torch.cat([tensor,tensor,tensor],dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [ ]:
print(tensor.mul(tensor))
print(tensor*tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
print(tensor.matmul(tensor.T))
print(tensor@tensor.T)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [ ]:
tensor.add_(5) # operations that have a _ suffix are in-place operations
print(tensor)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


__4. Bridge with NumPy__
- Tensors on the CPU and NumPy arrays can share their underlying memory locations.
- Changing one will change the other.

In [ ]:
t=torch.ones(5)
n=t.numpy()
print(t,n)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]


In [ ]:
t.add_(1)
print(t,n)

tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]


In [ ]:
n=np.ones(5)
t=torch.from_numpy(n)

In [ ]:
np.add(n,1,out=n)
print(t,n)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64) [2. 2. 2. 2. 2.]
